ITEM_DB = {
    # Even Items (Consumables, Swords, Axes, Rods, Whips, Spears, Tools, Bows, Armor, Shields)
    "01_Even": "Charred Newt", "02_Even": "Potion", "03_Even": "Hi-Potion", "04_Even": "Ex-Potion",
    "05_Even": "Magic Jar", "06_Even": "Hi-Magic", "07_Even": "Ex-Magic", "08_Even": "Regain",
    "09_Even": "Miracle", "0A_Even": "Antidote", "0B_Even": "Awake", "0C_Even": "Shriek",
    "0D_Even": "Mystery Pin", "0E_Even": "Power Gourd", "0F_Even": "Mind Gourd", "10_Even": "Magic Gourd",
    "11_Even": "Life Potion", "12_Even": "Spell Potion", "13_Even": "Power Potion", "14_Even": "Speed Potion",
    "15_Even": "Mind Potion", "16_Even": "Brave", "17_Even": "Pear Cider", "18_Even": "Sour Cider",
    "19_Even": "Lime Cider", "1A_Even": "Plum Cider", "1B_Even": "Apple Cider",
    "1C_Even": "Sleep Ball", "1D_Even": "Confuse Ball", "1E_Even": "Freeze Ball", "1F_Even": "Smoke Ball",
    "20_Even": "Ice Ball", "21_Even": "Fire Ball", "22_Even": "Terror Ball",
    "23_Even": "Ear Pick", "24_Even": "Boomerang", "25_Even": "Big Boomer", "26_Even": "Ex-boomer",
    "27_Even": "Dragon Tooth", "28_Even": "Green Tea", "29_Even": "Escape", "2A_Even": "Warp",
    "2B_Even": "Dragon Egg", "2C_Even": "Curselifter", "2D_Even": "Providence", "2E_Even": "Secret Fruit",
    "2F_Even": "Holy Fruit", "30_Even": "Breeze Fruit", "31_Even": "Charm Fruit", "32_Even": "Dark Fruit",
    "33_Even": "Earth Fruit", "34_Even": "Flame Fruit", "35_Even": "Magic Fruit",
    # Swords
    "36_Even": "Dual Blade", "37_Even": "Frypan", "38_Even": "Knife", "39_Even": "Small Knife",
    "3A_Even": "Rapier", "3B_Even": "Battle Knife", "3C_Even": "Dagger", "3D_Even": "Insect Crush",
    "3E_Even": "Long Knife", "3F_Even": "Short Sword", "40_Even": "Light Knife", "41_Even": "Kukri",
    "42_Even": "Gladius", "43_Even": "Cold Rapier", "44_Even": "Scimitar", "45_Even": "Deadly Sword",
    "47_Even": "SurhCustom11", "48_Even": "Bronze Sword", "49_Even": "Fire Dagger", "4A_Even": "War Rapier",
    "4B_Even": "Long Sword", "4C_Even": "Berserk Blade", "4E_Even": "Multi Sword", "4F_Even": "Rockbreaker",
    "50_Even": "Broad Sword", "51_Even": "Estok", "52_Even": "Silvo Rapier", "53_Even": "Burn Sword",
    "54_Even": "Decar Blade", "55_Even": "Crazy Blade", "56_Even": "Deadly Sword", "58_Even": "Luck Rapier",
    "5A_Even": "Aqua Sword", "5B_Even": "Red Saber", "5C_Even": "Lucky Blade", "5E_Even": "Mist Rapier",
    "5F_Even": "Boom Sword", "60_Even": "Freeze Sword", "61_Even": "Silver Sword", "62_Even": "Flying Blow",
    "63_Even": "Super Sword", "64_Even": "Buster Sword", "65_Even": "Rune Rapier", "66_Even": "Old Sword",
    "67_Even": "Lizard Blow", "68_Even": "Zirco Sword", "69_Even": "Sizzle Sword", "6A_Even": "Blaze Sword",
    "6B_Even": "Myth Sword", "6C_Even": "Gades Blade", "6D_Even": "Sky Sword", "6E_Even": "Snow Sword",
    "6F_Even": "Fry Sword", "70_Even": "Egg Sword",
    # Axes / Rods / Whips / Spears
    "71_Even": "Franshiska", "72_Even": "Thunder Ax", "73_Even": "Hand Ax", "74_Even": "Bronze Ax",
    "75_Even": "Flying Ax", "76_Even": "Rainy Ax", "77_Even": "Great Ax", "78_Even": "Zirco Ax", "79_Even": "Mega Ax",
    "7A_Even": "Mace", "7B_Even": "Rod", "7C_Even": "Staff", "7D_Even": "Deadly Rod", "7F_Even": "Sleepy Rod",
    "80_Even": "Long Staff", "81_Even": "Holy Staff", "82_Even": "Morning", "83_Even": "Pounder Rod",
    "84_Even": "Crystal Wand", "85_Even": "Silver Rod", "86_Even": "Zirco Rod", "87_Even": "Zirco Flail", "88_Even": "Spark Staff",
    "89_Even": "Whip", "8A_Even": "Wire", "8B_Even": "Chain", "8C_Even": "Aqua Whip", "8D_Even": "Cutter Whip",
    "8E_Even": "Royal Whip", "8F_Even": "Holy Whip", "90_Even": "Zirco Whip", "91_Even": "Air Whip",
    "92_Even": "Fatal Pick", "93_Even": "Fatal Pick", "94_Even": "Spear", "95_Even": "Trident",
    "96_Even": "Halberd", "97_Even": "Heavy Lance", "98_Even": "Water Spear", "99_Even": "Dragon Spear",
    "9A_Even": "Vice Pliers", "9B_Even": "Coma Hit", "9C_Even": "Figgoru", "9D_Even": "Superdriver",
    "9E_Even": "Stun Gun", "9F_Even": "Battledriver", "A0_Even": "Launcher", "A1_Even": "Freeze Bow",
    "A2_Even": "Cursed Bow", "A3_Even": "Arty's Bow",
    "A4_Even": "Apron", "A5_Even": "Dress", "A6_Even": "Cloth", "A7_Even": "Lab-coat",
    "A8_Even": "Hide Armor", "A9_Even": "Frock", "AA_Even": "Robe", "AB_Even": "Cloth Armor",
    "AC_Even": "Coat", "AD_Even": "Tough Hide", "AE_Even": "Light Dress", "AF_Even": "Light Armor",
    "B0_Even": "Camu Armor", "B1_Even": "Baggy", "B2_Even": "Tight Dress", "B3_Even": "Chainmail",
    "B4_Even": "Holy Wings", "B5_Even": "Ironmail", "B6_Even": "Toga", "B7_Even": "Chain Armor",
    "B8_Even": "Thick Cloth", "B9_Even": "Stone Plate", "BA_Even": "Long Robe", "BB_Even": "Plated Cloth",
    "BC_Even": "Iron Plate", "BD_Even": "Metal Mail", "BE_Even": "Silk Toga", "BF_Even": "Silver Armor",
    
    # Odd Items (Shields, Helmets, Rings, Rocks, Misc, Scenario)
    "00_Odd": "Gauntlet", "01_Odd": "Rune Gloves", "02_Odd": "Holy Shield", "03_Odd": "Zirco Gloves",
    "04_Odd": "Zirco Shield", "05_Odd": "Old Shield", "06_Odd": "Flame Shield", "07_Odd": "Water Gaunt",
    "08_Odd": "Bolt Shield", "09_Odd": "Cryst Shield", "0A_Odd": "Mega Shield", "0B_Odd": "Dark Mirror",
    "0D_Odd": "Apron Shield", "0E_Odd": "Pearl Shield",
    # Helmets
    "0F_Odd": "Pot", "10_Odd": "Beret", "11_Odd": "Cap", "12_Odd": "Cloth Helmet", "13_Odd": "Hairband",
    "14_Odd": "Headband", "15_Odd": "Hide Helmet", "16_Odd": "Jet Helm", "17_Odd": "Red Beret",
    "18_Odd": "Glass Cap", "19_Odd": "Wood Helmet", "1A_Odd": "Blue Beret", "1B_Odd": "Brone Helm",
    "1C_Odd": "Stone Helm", "1D_Odd": "Cloche", "1E_Odd": "Fury Helm", "1F_Odd": "Iron Helm",
    "20_Odd": "Tight Helm", "21_Odd": "Turban", "22_Odd": "Plate Cap", "23_Odd": "Roomy Helm",
    "24_Odd": "Tight Turban", "25_Odd": "Glass Cloche", "26_Odd": "Plate Helm", "27_Odd": "Rock Helmet",
    "28_Odd": "Jute Helmet", "29_Odd": "Shade Hat", "2A_Odd": "Metal Cloche", "2B_Odd": "Silver Helmet",
    "2C_Odd": "Fury Ribbon", "2D_Odd": "Silver Hat", "2E_Odd": "Eron Hat", "2F_Odd": "Circlet",
    "30_Odd": "Golden Helm", "31_Odd": "Gold Band", "32_Odd": "Plati Band", "33_Odd": "Plati Helm",
    "34_Odd": "Crysto Beret", "35_Odd": "Crysto Helm", "36_Odd": "Holy Cap", "37_Odd": "Safety Hat",
    "38_Odd": "Zirco Band", "39_Odd": "Zirco Helmet", "3A_Odd": "Old Helmet", "3B_Odd": "Agony Helmet",
    "3C_Odd": "Boom Turban", "3D_Odd": "Aqua Helm", "3E_Odd": "Ice Hairband", "3F_Odd": "Legend Helm",
    "40_Odd": "Hairpin", "41_Odd": "Brill Helm", "42_Odd": "Pearl Helmet",
    # Rings
    "43_Odd": "Ear Jewel", "44_Odd": "Glass Brac", "45_Odd": "Glass Ring", "46_Odd": "Earring",
    "47_Odd": "Speedy Ring", "48_Odd": "Power Ring", "49_Odd": "Muscle Ring", "4A_Odd": "Protect Ring",
    "4B_Odd": "Wind Ring", "4C_Odd": "Witch Ring", "4D_Odd": "Fire Ring", "4E_Odd": "Water Ring",
    "4F_Odd": "Ice Ring", "50_Odd": "Thunder Ring", "51_Odd": "Fury Ring", "52_Odd": "Mystery Ring",
    "53_Odd": "Sonic Ring", "54_Odd": "Hipower Ring", "55_Odd": "Trick Ring", "56_Odd": "Fake Ring",
    "57_Odd": "S-Fire Ring", "58_Odd": "S-Water Ring", "59_Odd": "S-Ice Ring", "5A_Odd": "S-Thun Ring",
    "5B_Odd": "S-Power Ring", "5C_Odd": "S-Mind Ring", "5D_Odd": "S-Pro Ring", "5E_Odd": "S-Witch Ring",
    "5F_Odd": "Undead Ring", "60_Odd": "Rocket Ring", "61_Odd": "Ghost Ring", "62_Odd": "Angry Ring",
    "63_Odd": "S-Myst Ring", "64_Odd": "Dia Ring", "65_Odd": "Sea Ring", "66_Odd": "Dragon Ring",
    "67_Odd": "Engage Ring", "68_Odd": "Egg Ring",
    # Rocks
    "69_Odd": "Horse Rock", "6A_Odd": "Eagle Rock", "6B_Odd": "Lion Fang", "6C_Odd": "Bee Rock",
    "6D_Odd": "Snake Rock", "6E_Odd": "Cancer Rock", "6F_Odd": "Pumpkin Jewel", "70_Odd": "Uni Jewel",
    "71_Odd": "Mysto Jewel", "72_Odd": "Samu Jewel", "73_Odd": "Bat Rock", "74_Odd": "Hidora Rock",
    "75_Odd": "Flame Jewel", "76_Odd": "Water Jewel", "77_Odd": "Thundo Jewel", "78_Odd": "Earth Jewel",
    "79_Odd": "Twist Jewel", "7A_Odd": "Gloom Jewel", "7B_Odd": "Tidal Jewel", "7C_Odd": "Magma Rock",
    "7D_Odd": "Evil Jewel", "7F_Odd": "Gorgon Rock", "80_Odd": "Song Rock", "81_Odd": "Kraken Rock",
    "82_Odd": "Catfish Jewel", "83_Odd": "Camu Jewel", "84_Odd": "Spido Jewel", "85_Odd": "Gorgon Rock",
    "86_Odd": "Light Jewel", "87_Odd": "Black Eye", "88_Odd": "Silver Eye", "89_Odd": "Gold Eye",
    # Misc / Scenario
    "8A_Odd": "1 Coin", "8B_Odd": "10 Coin Set", "8C_Odd": "50 Coin Set", "8D_Odd": "100 Coin Set",
    "8E_Odd": "Flame Charm", "8F_Odd": "Zap Charm", "90_Odd": "Magic Lamp", "91_Odd": "Statue",
    "92_Odd": "Rage Knife", "93_Odd": "Fortune Whip", "94_Odd": "Dragon Blade", "95_Odd": "Bunny Ring",
    "96_Odd": "Bunny Ears", "97_Odd": "Bunnylady", "98_Odd": "Bunny Sword", "99_Odd": "Bunnysuit",
    "A7_Odd": "Hook", "A8_Odd": "Bomb", "A9_Odd": "Arrow", "AA_Odd": "Fire Arrow", "AB_Odd": "Hammer"
}
