MAP_DB = {
    "00": "World Map", "01": "Map of Seafloor", "02": "Arek Daos Shrine", "03": "Elcid (Outside)", "04": "Elcid (Inside)",
    "05": "Secret Skills Cave", "06": "Cave to Sundletan B1", "07": "Cave to Sundletan B2", "08": "Sundletan (Outside)", "09": "Sundletan (Inside)",
    "0A": "Lake Cave B1", "0B": "Lake Cave B2", "0C": "Lake Cave B3", "0D": "Shrine to Alunze Kingdom", "0E": "Foomy Woods",
    "0F": "Alunze Castle 1F", "10": "Alunze Castle 2F", "11": "Alunze Castle B2", "12": "Alunze Castle B3", "13": "Alunze Castle B4",
    "14": "Alunze Castle B5", "15": "Alunze Kingdom (Outside)", "16": "Alunze Kingdom (Inside)", "17": "Alunze North Shrine",
    "18": "Alunze Northwest Cave B1", "19": "Alunze Northwest Cave B2", "1A": "Alunze Northwest Cave B3", "1B": "Alunze Northwest Cave B4",
    "1C": "Tanbel (Outside)", "1D": "Tanbel (Inside)", "1E": "Tanbel Unknown", "1F": "Tanbel Southeast Tower 1F",
    "20": "Tanbel Southeast Tower 2F", "21": "Tanbel Southeast Tower 3F", "22": "Tanbel Southeast Tower 4F",
    "23": "Tanbel Southeast Tower 5F", "24": "Tanbel Southeast Tower 6F", "25": "Clamento (Outside)", "26": "Clamento (Inside)",
    "27": "Ruby Cave B1", "28": "Ruby Cave B2", "29": "Ruby Cave B3", "2A": "Ruby Cave B4",
    "2B": "Small Shrine to Parcelyte", "2C": "Parcelyte (Outside)", "2D": "Parcelyte (Inside)", "2E": "Parcelyte Castle 1F", "2F": "Parcelyte Castle 2F",
    "30": "Treasure Sword Shrine 1F", "31": "Treasure Sword Shrine 2F", "32": "Treasure Sword Shrine 3F",
    "33": "Treasure Sword Shrine 4F", "34": "Treasure Sword Shrine B1", "35": "Small Shrine to Gordovan", "36": "Gordovan",
    "37": "Gordovan Unknown", "38": "Gordovan West Tower 1F", "39": "Gordovan West Tower 2F", "3A": "Gordovan West Tower 3F",
    "3B": "Gordovan West Tower 4F", "3C": "Gordovan West Tower 5F", "3D": "Gordovan West Tower 6F",
    "3E": "Merix Village (Outside)", "3F": "Merix Village (Inside)", "40": "Cave Bridge B1", "41": "Cave Bridge B2",
    "42": "Cave Bridge B3", "43": "Cave Bridge B4", "44": "Cave Bridge B5", "45": "Bound Kingdom (Outside)", "46": "Bound Kingdom (Inside)",
    "47": "North Dungeon B1", "48": "North Dungeon B2", "49": "North Dungeon B3", "4A": "North Dungeon B4", "4B": "North Dungeon Unknown",
    "4C": "Ancient Tower 1F", "4D": "Ancient Tower 2F", "4E": "Ancient Tower 3F", "4F": "Ancient Tower 4F", "50": "Ancient Tower 5F",
    "51": "Ancient Tower 6F", "52": "Ancient Tower 7F", "53": "Ancient Tower 6F Alt", "54": "Ancient Tower 5F Alt", "55": "Ancient Tower 4F Alt",
    "56": "Small Shrine to Aleyn", "57": "Aleyn Unknown", "58": "North Lighthouse 1F", "59": "North Lighthouse 2F",
    "5A": "North Lighthouse 3F", "5B": "North Lighthouse 4F", "5C": "North Lighthouse 5F", "5D": "North Lighthouse 6F",
    "5E": "Port Town of Aleyn (Outside)", "5F": "Port Town of Aleyn (Inside)", "60": "Phantom Tree Mountain",
    "61": "Phantom Cave 1", "62": "Phantom Cave 2", "63": "Phantom Cave 3", "64": "Phantom Cave 4", "65": "Phantom Cave 5", "66": "Phantom Cave 6", "67": "Phantom Cave 7",
    "68": "Gruberik (Outside)", "69": "Gruberik (Inside)", "6A": "Narcysus (Outside)", "6B": "Narcysus (Inside)", "6C": "Narcysus Unknown",
    "6D": "Tower of Sacrifice 1F", "6E": "Tower of Sacrifice 2F", "6F": "Tower of Sacrifice 3F", "70": "Tower of Sacrifice 4F",
    "71": "Tower of Sacrifice 5F", "72": "Tower of Sacrifice 6F", "73": "Karlloon (Outside)", "74": "Karlloon (Inside)",
    "75": "Karlloon North Shrine 1F", "76": "Karlloon North Shrine 2F", "77": "Karlloon North Shrine 3F", "78": "Karlloon North Shrine B1",
    "79": "Small Shrine to Treadool", "7A": "Treadool (Outside)", "7B": "Treadool (Inside)", "7C": "Treadool Unknown",
    "7D": "Lexis Shaia Laboratory", "7E": "Flower Mountain 1", "7F": "Flower Mountain 2", "80": "Flower Mountain 3",
    "81": "Flower Mountain 4", "82": "Flower Mountain 5", "83": "Flower Mountain 6", "84": "Flower Mountain 7",
    "85": "Forfeit Island (Outside)", "86": "Forfeit Island (Inside)", "87": "Markao", "88": "Dankirk Kingdom (Outside)", "89": "Dankirk Kingdom (Inside)",
    "8A": "Auralio Kingdom (Outside)", "8B": "Auralio Kingdom (Inside)", "8C": "Dankirk North Cave B1", "8D": "Dankirk North Cave B2",
    "8E": "Dankirk North Cave B3", "8F": "Dankirk North Cave B4", "90": "Dankirk North Cave B5", "91": "Ferim Kingdom (Outside)", "92": "Ferim Kingdom (Inside)",
    "93": "Ferim Unknown", "94": "Northeast Tower 1F", "95": "Northeast Tower 2F", "96": "Northeast Tower 3F", "97": "Northeast Tower 4F",
    "98": "Northeast Tower 5F", "99": "Small Shrine to Agurio", "9A": "Agurio", "9B": "Treble (Outside)", "9C": "Treble (Inside)",
    "9D": "Pico Forest (Outside)", "9E": "Pico Forest (Inside)", "9F": "Small Shrine to Dragon Egg", "A0": "Portravia (Outside)", "A1": "Portravia (Inside)",
    "A2": "Kirmo Laboratory", "A3": "Mountain of No Return 1", "A4": "Mountain of No Return 2", "A5": "Mountain of No Return 3",
    "A6": "Eserikto (Outside)", "A7": "Eserikto (Inside)", "A8": "Divine Shrine 1F", "A9": "Divine Shrine 2F", "AA": "Divine Shrine 3F", "AB": "Divine Shrine B1",
    "AC": "Barnan (Outside)", "AD": "Barnan (Inside)", "AE": "Barnan Sth. Submarine Cave", "AF": "Shrine of Vengeance 1F",
    "B0": "Shrine of Vengeance 2F", "B1": "Shrine of Vengeance 3F", "B2": "Shrine of Vengeance 4F", "B3": "Shrine of Vengeance B1", "B4": "Shrine of Vengeance B2",
    "B5": "Durale (Outside)", "B6": "Durale (Inside)", "B7": "Durale Unknown", "B8": "Tower of Truth 1F", "B9": "Tower of Truth 2F",
    "BA": "Tower of Truth 3F", "BB": "Tower of Truth 4F", "BC": "Tower of Truth 5F", "BD": "Tower of Truth 6F", "BE": "Chaed (Outside)", "BF": "Chaed (Inside)",
    "C0": "Dragon Mountain 1", "C1": "Dragon Mountain 2", "C2": "Dragon Mountain 3", "C3": "Dragon Mountain 4",
    "C4": "Dragon Mountain 5", "C5": "Dragon Mountain 6", "C6": "Dragon Mountain 7", "C7": "Dragon Mountain 8",
    "C8": "Chaed Nth. Submarine Cave", "C9": "Submarine Town of Preamarl (Outside)", "CA": "Submarine Town of Preamarl (Inside)",
    "CB": "Submarine Cave to Shrine 1", "CC": "Submarine Cave to Shrine 2", "CD": "Submarine Cave Shrine 1", "CE": "Submarine Cave Shrine 2",
    "CF": "Submarine Cave Shrine Unknown", "D0": "Chaed Alternate", "D1": "Gratze Sth. Submarine Cave", "D2": "Gratze Castle B1",
    "D3": "Gratze Castle B2", "D4": "Gratze Castle B3", "D5": "Gratze Castle B4", "D6": "Gratze Kingdom (Outside)", "D7": "Gratze Kingdom (Inside)",
    "D8": "Narvick", "D9": "Narvick Inside", "DA": "Narvick Unknown 1", "DB": "Narvick Unknown 2", "DC": "Narvick Unknown 3",
    "DD": "Shuman Isl. Sealed Tower", "DE": "Shuman Unknown 1", "DF": "Shuman Unknown 2", "E0": "Shuman Unknown 3",
    "E1": "Strahda Isl. Sealed Tower", "E2": "Strahda Unknown 1", "E3": "Strahda Unknown 2", "E4": "Strahda Unknown 3",
    "E5": "Kamirno Isl. Sealed Tower", "E6": "Kamirno Unknown", "E7": "Shrine of Daos 1F", "E8": "Shrine of Daos 2F",
    "E9": "Shrine of Daos 3F", "EA": "Shrine of Daos 4F", "EB": "Shrine of Daos 5F", "EC": "Shrine of Daos Unknown",
    "ED": "Capsule Monsters Shrine", "EE": "Capsule Monsters Cave Unknown", "EF": "Capsule Monsters Cave", "F0": "Ancient Cave", "F1": "Ancient Cave Final Floor",
    "F2": "Unknown F2", "F3": "Unknown F3", "F4": "Unknown F4", "F5": "Unknown F5", "F6": "Unknown F6",
    "F7": "Unknown F7", "F8": "Unknown F8", "F9": "Unknown F9", "FA": "Unknown FA", "FB": "Unknown FB",
    "FC": "Unknown FC", "FD": "Unknown FD", "FE": "Unknown FE", "FF": "Unknown FF"
}
